"""create tables

Revision ID: 537980e0b839
Revises: 
Create Date: 2023-12-19 01:11:08.808353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '537980e0b839'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('air_quality_nyc')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('air_quality_nyc',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('unique_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('indicator_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('measure', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('measure_info', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('geo_type_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('geo_join_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('geo_place_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('time_period', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_value', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
